<a href="https://colab.research.google.com/github/Pallavisangral/BookReccomendationSystem/blob/main/phase1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
books =pd.read_csv(r"C:\Users\PALLAVI\Desktop\python-learn\learning-phase\Books.csv", low_memory=False, index_col =0)

In [ ]:
books.head(5)

,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
ISBN,,,,,,,
0195153448,Classical Mythology,Mark P. O. Morford,2002,Oxford University Press,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...
0002005018,Clara Callan,Richard Bruce Wright,2001,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...
0060973129,Decision in Normandy,Carlo D'Este,1991,HarperPerennial,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...
0374157065,Flu: The Story of the Great Influenza Pandemic...,Gina Bari Kolata,1999,Farrar Straus Giroux,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...
0393045218,The Mummies of Urumchi,E. J. W. Barber,1999,W. W. Norton &amp; Company,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...

In [ ]:
len(books)

271360

In [ ]:
rating=pd.read_csv(r"C:\Users\PALLAVI\Desktop\python-learn\learning-phase\Ratings.csv")

In [ ]:
rating.head(5)

   User-ID        ISBN  Book-Rating
0   276725  034545104X            0
1   276726  0155061224            5
2   276727  0446520802            0
3   276729  052165615X            3
4   276729  0521795028            6

In [ ]:
len(rating)

1149780

In [ ]:
description = pd.read_csv(r"C:\Users\PALLAVI\Desktop\python-learn\learning-phase\Books_Descriptions.csv", index_col =0)

In [ ]:
description.head(5)

          ISBN                                        description
3   0451407423  A high-tech submarine thriller follows Admiral...
4   0373290284  The Flower And The Sword by Jacqueline Navin r...
23  0671423886  In late-fifteenth-century Spain, the indomitab...
25  082176618X  Mountain man Smoke Jensen comes to the aid of ...
27  0380789108  Stephanie promises to help the ghost of her ne...

In [ ]:
unnamed_cols= description.columns.str.contains('Unnamed: 0')
description= description.drop(description[description.columns[unnamed_cols]], axis=1)

In [ ]:
description.head(5)

         ISBN                                        description
0  0451407423  A high-tech submarine thriller follows Admiral...
1  0373290284  The Flower And The Sword by Jacqueline Navin r...
2  0671423886  In late-fifteenth-century Spain, the indomitab...
3  082176618X  Mountain man Smoke Jensen comes to the aid of ...
4  0380789108  Stephanie promises to help the ghost of her ne...

merging books.csv and description.csv files

In [ ]:
mergedbookdes =pd.merge(books,description,on ='ISBN')

In [ ]:
# mergedbookdes.to_csv(r"C:\Users\PALLAVI\Desktop\python-learn\learning-phase\merged.csv")

In [ ]:
mergedbookdes.head(5)

,ISBN,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L,description
0,0684823802,OUT OF THE SILENT PLANET,C.S. Lewis,1996,Scribner,http://images.amazon.com/images/P/0684823802.0...,http://images.amazon.com/images/P/0684823802.0...,http://images.amazon.com/images/P/0684823802.0...,Dr. Ransom is abducted to the eerie red planet...
1,0679810307,Shabanu: Daughter of the Wind (Border Trilogy),SUZANNE FISHER STAPLES,1991,Laurel Leaf,http://images.amazon.com/images/P/0679810307.0...,http://images.amazon.com/images/P/0679810307.0...,http://images.amazon.com/images/P/0679810307.0...,"Shabanu, a young nomad of the Cholistan Desert..."
2,0345260317,The Dragons of Eden: Speculations on the Evolu...,Carl Sagan,1978,Ballantine Books,http://images.amazon.com/images/P/0345260317.0...,http://images.amazon.com/images/P/0345260317.0...,http://images.amazon.com/images/P/0345260317.0...,Dr. Carl Sagan Takes Us on a Great Reading Adv...
3,0671042858,The Girl Who Loved Tom Gordon,Stephen King,2000,Pocket,http://images.amazon.com/images/P/0671042858.0...,http://images.amazon.com/images/P/0671042858.0...,http://images.amazon.com/images/P/0671042858.0...,The acclaimed #1 New York Times and undisputed...
4,037582345X,"The Golden Compass (His Dark Materials, Book 1)",PHILIP PULLMAN,2002,Knopf Books for Young Readers,http://images.amazon.com/images/P/037582345X.0...,http://images.amazon.com/images/P/037582345X.0...,http://images.amazon.com/images/P/037582345X.0...,Living among scholars in the hallowed halls of...

In [ ]:
len(mergedbookdes)

7021

In [ ]:
mergedbookdes.to_csv("datawithindex.csv")

In [ ]:
data = pd.read_csv(r'C:\Users\PALLAVI\Desktop\python-learn\learning-phase\datawithindex.csv', index_col =0)
data

,ISBN,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L,description
0,0684823802,OUT OF THE SILENT PLANET,C.S. Lewis,1996,Scribner,http://images.amazon.com/images/P/0684823802.0...,http://images.amazon.com/images/P/0684823802.0...,http://images.amazon.com/images/P/0684823802.0...,Dr. Ransom is abducted to the eerie red planet...
1,0679810307,Shabanu: Daughter of the Wind (Border Trilogy),SUZANNE FISHER STAPLES,1991,Laurel Leaf,http://images.amazon.com/images/P/0679810307.0...,http://images.amazon.com/images/P/0679810307.0...,http://images.amazon.com/images/P/0679810307.0...,"Shabanu, a young nomad of the Cholistan Desert..."
2,0345260317,The Dragons of Eden: Speculations on the Evolu...,Carl Sagan,1978,Ballantine Books,http://images.amazon.com/images/P/0345260317.0...,http://images.amazon.com/images/P/0345260317.0...,http://images.amazon.com/images/P/0345260317.0...,Dr. Carl Sagan Takes Us on a Great Reading Adv...
3,0671042858,The Girl Who Loved Tom Gordon,Stephen King,2000,Pocket,http://images.amazon.com/images/P/0671042858.0...,http://images.amazon.com/images/P/0671042858.0...,http://images.amazon.com/images/P/0671042858.0...,The acclaimed #1 New York Times and undisputed...
4,037582345X,"The Golden Compass (His Dark Materials, Book 1)",PHILIP PULLMAN,2002,Knopf Books for Young Readers,http://images.amazon.com/images/P/037582345X.0...,http://images.amazon.com/images/P/037582345X.0...,http://images.amazon.com/images/P/037582345X.0...,Living among scholars in the hallowed halls of...
...,...,...,...,...,...,...,...,...,...
7016,0373123914,The Outback Marriage Ransom (Harlequin Presents),Emma Darcy,2004,Harlequin,http://images.amazon.com/images/P/0373123914.0...,http://images.amazon.com/images/P/0373123914.0...,http://images.amazon.com/images/P/0373123914.0...,Ric Donato wanted Lara Seymour. But Ric was a ...
7017,0751506451,The Maiden (The Morland Dynasty Series),Cynthia Harrod-Eagles,2001,Little Brown UK Ltd,http://images.amazon.com/images/P/0751506451.0...,http://images.amazon.com/images/P/0751506451.0...,http://images.amazon.com/images/P/0751506451.0...,1720: political intrigue besets the kingdom as...
7018,0896382338,"My Child, My Teacher, My Friend: One Man's Vie...",Dwight Lee Wolter,1991,Hazelden,http://images.amazon.com/images/P/0896382338.0...,http://images.amazon.com/images/P/0896382338.0...,http://images.amazon.com/images/P/0896382338.0...,A collection of essays on parenting explains h...
7019,082811420X,What I Know Now,Bill J. Bonnstetter,1999,Forbes Inc,http://images.amazon.com/images/P/082811420X.0...,http://images.amazon.com/images/P/082811420X.0...,http://images.amazon.com/images/P/082811420X.0...,"Every person needs to discover the ""why"" behin..."
7020,0762412119,"Burpee Gardening Cyclopedia: A Concise, Up to ...",Allan Armitage,2002,Running Press Book Publishers,http://images.amazon.com/images/P/0762412119.0...,http://images.amazon.com/images/P/0762412119.0...,http://images.amazon.com/images/P/0762412119.0...,"A definitive, compact guide to gardening for n..."

In [ ]:
mergedbookdes = mergedbookdes.drop(['Image-URL-M','Image-URL-L'], axis = 1 )

KeyError: "['Image-URL-M', 'Image-URL-L'] not found in axis"

In [ ]:
mergedbookdes.rename(columns = { 'ISBN': 'isbn', 'Book-Author':'author', 'Book-Title':'title', 'Publisher': 'publisher','description':'summary' , 'Image-URL-S': 'images'
                              }, inplace = True)

In [ ]:
mergedbookdes.to_csv("bookdes1.csv", index_col = 0 )

TypeError: NDFrame.to_csv() got an unexpected keyword argument 'index_col'

merging books.csv, description.csv and ratings.csv

In [ ]:
completebook = pd.merge(mergedbookdes,rating, on = 'ISBN')

In [ ]:
completebook.head(5)

,ISBN,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L,description,User-ID,Book-Rating
0,0684823802,OUT OF THE SILENT PLANET,C.S. Lewis,1996,Scribner,http://images.amazon.com/images/P/0684823802.0...,http://images.amazon.com/images/P/0684823802.0...,http://images.amazon.com/images/P/0684823802.0...,Dr. Ransom is abducted to the eerie red planet...,17,0
1,0684823802,OUT OF THE SILENT PLANET,C.S. Lewis,1996,Scribner,http://images.amazon.com/images/P/0684823802.0...,http://images.amazon.com/images/P/0684823802.0...,http://images.amazon.com/images/P/0684823802.0...,Dr. Ransom is abducted to the eerie red planet...,13594,0
2,0684823802,OUT OF THE SILENT PLANET,C.S. Lewis,1996,Scribner,http://images.amazon.com/images/P/0684823802.0...,http://images.amazon.com/images/P/0684823802.0...,http://images.amazon.com/images/P/0684823802.0...,Dr. Ransom is abducted to the eerie red planet...,65258,0
3,0684823802,OUT OF THE SILENT PLANET,C.S. Lewis,1996,Scribner,http://images.amazon.com/images/P/0684823802.0...,http://images.amazon.com/images/P/0684823802.0...,http://images.amazon.com/images/P/0684823802.0...,Dr. Ransom is abducted to the eerie red planet...,98930,7
4,0684823802,OUT OF THE SILENT PLANET,C.S. Lewis,1996,Scribner,http://images.amazon.com/images/P/0684823802.0...,http://images.amazon.com/images/P/0684823802.0...,http://images.amazon.com/images/P/0684823802.0...,Dr. Ransom is abducted to the eerie red planet...,122988,0

In [ ]:
len(completebook)

27122

In [ ]:
completebook.isnull().sum()

ISBN                   0
Book-Title             0
Book-Author            0
Year-Of-Publication    0
Publisher              0
Image-URL-S            0
Image-URL-M            0
Image-URL-L            0
description            0
User-ID                0
Book-Rating            0
dtype: int64

In [ ]:
print(completebook.duplicated().sum())

0

count of number of users rating the book

In [ ]:
counted=completebook.groupby("ISBN").count()['Book-Rating'].reset_index(name="rating-count")
counted

            ISBN  rating-count
0     0001714236             1
1     0001841572             2
2     0002233495             1
3     0002553686             1
4     0004589777             1
...          ...           ...
7016  9625939385             1
7017  9681508122             1
7018  9712703487             1
7019  9768163089             1
7020  9871138105             1

[7021 rows x 2 columns]

In [ ]:
# completebook1=pd.merge(counted,completebook, on='ISBN', how= "inner")

count averge of complete book

In [ ]:
average=completebook.groupby("ISBN").mean()['Book-Rating'].reset_index(name="average-rating")
average

C:\Users\PALLAVI\AppData\Local\Temp\ipykernel_1852\1616484041.py:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  average=completebook.groupby("ISBN").mean()['Book-Rating'].reset_index(name="average-rating")

            ISBN  average-rating
0     0001714236             0.0
1     0001841572             2.5
2     0002233495             0.0
3     0002553686             0.0
4     0004589777             0.0
...          ...             ...
7016  9625939385             0.0
7017  9681508122             0.0
7018  9712703487             0.0
7019  9768163089             0.0
7020  9871138105             0.0

[7021 rows x 2 columns]

merging average rating and rating count into single data frame

In [ ]:
merged = pd.merge(counted,average, on = 'ISBN', how = 'inner')
merged.head(5)

         ISBN  rating-count  average-rating
0  0001714236             1             0.0
1  0001841572             2             2.5
2  0002233495             1             0.0
3  0002553686             1             0.0
4  0004589777             1             0.0

In [ ]:
# merged =merged.sort_values('average-rating', ascending =False)

In [ ]:
# merged =merged.sort_values('rating-count', ascending =False)

In [ ]:
merged.head(20)

          ISBN  rating-count  average-rating
0   0001714236             1        0.000000
1   0001841572             2        2.500000
2   0002233495             1        0.000000
3   0002553686             1        0.000000
4   0004589777             1        0.000000
5   0006278663             1        0.000000
6   0006380905             2        0.000000
7   000638255X             1        0.000000
8   0006472648             6        2.333333
9   0006497985             2        0.000000
10  0006550649            11        1.909091
11  000692848X             1        0.000000
12  0007100353             1        0.000000
13  0007106580             3        0.000000
14  0007116497             3        3.333333
15  0007137559             1        0.000000
16  0007148119             1        0.000000
17  0007156111             2        2.500000
18  0007163665             3        0.000000
19  0007640617             1        0.000000

In [ ]:
len(merged)

7021

get books having rating count more than or equal to 50

In [ ]:
popularbooks = merged[merged['rating-count'] >= 100 ]
# popularbooks=popularbooks[popularbooks['average-rating'] >=3] 
popularbooks.head(5)

            ISBN  rating-count  average-rating
291   0061097101           219        2.835616
1206  034536676X           108        4.472222
2375  0425116840           166        1.831325
2389  0425158632           115        1.773913
2425  0425185710           105        2.752381

In [ ]:
len(popularbooks)

15

top 10 books according to average rating

In [ ]:
mostpopularbooks = popularbooks.sort_values('average-rating', ascending =False)

In [ ]:
mostpopularbooks

            ISBN  rating-count  average-rating
1206  034536676X           108        4.472222
5542  0871136791           191        3.308901
3848  0671042858           214        3.135514
2516  0440211727           517        2.976789
291   0061097101           219        2.835616
4157  0679731725           102        2.823529
2425  0425185710           105        2.752381
4532  0743411250           136        2.727941
3155  0515130389           174        2.574713
3159  0515133302           109        2.513761
3916  0671568175           136        2.213235
3477  0553572326           110        2.209091
2375  0425116840           166        1.831325
2389  0425158632           115        1.773913
2755  0449134482           121        1.570248

In [ ]:
top10books2 = mostpopularbooks.head(10)
top10books2

            ISBN  rating-count  average-rating
1206  034536676X           108        4.472222
5542  0871136791           191        3.308901
3848  0671042858           214        3.135514
2516  0440211727           517        2.976789
291   0061097101           219        2.835616
4157  0679731725           102        2.823529
2425  0425185710           105        2.752381
4532  0743411250           136        2.727941
3155  0515130389           174        2.574713
3159  0515133302           109        2.513761

In [ ]:
recomdata = pd.merge(mergedbookdes, top10books2, on = 'ISBN', how = 'inner')

In [ ]:
recomdata.head(10)

,ISBN,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L,description,rating-count,average-rating
0,0671042858,The Girl Who Loved Tom Gordon,Stephen King,2000,Pocket,http://images.amazon.com/images/P/0671042858.0...,http://images.amazon.com/images/P/0671042858.0...,http://images.amazon.com/images/P/0671042858.0...,The acclaimed #1 New York Times and undisputed...,214,3.135514
1,0440211727,A Time to Kill,JOHN GRISHAM,1992,Dell,http://images.amazon.com/images/P/0440211727.0...,http://images.amazon.com/images/P/0440211727.0...,http://images.amazon.com/images/P/0440211727.0...,Following the brutal rape of his ten-year-old ...,517,2.976789
2,0425185710,Valhalla Rising (Dirk Pitt Adventures (Paperba...,Clive Cussler,2002,Berkley Publishing Group,http://images.amazon.com/images/P/0425185710.0...,http://images.amazon.com/images/P/0425185710.0...,http://images.amazon.com/images/P/0425185710.0...,Marine explorer Dirk Pitt must rely on the nau...,105,2.752381
3,0515130389,Carolina Moon,Nora Roberts,2001,Jove Books,http://images.amazon.com/images/P/0515130389.0...,http://images.amazon.com/images/P/0515130389.0...,http://images.amazon.com/images/P/0515130389.0...,From the #1 New York Times bestselling author-...,174,2.574713
4,0743411250,The Woman Next Door,Barbara Delinsky,2002,Pocket,http://images.amazon.com/images/P/0743411250.0...,http://images.amazon.com/images/P/0743411250.0...,http://images.amazon.com/images/P/0743411250.0...,New York Times bestselling author Barbara Deli...,136,2.727941
5,0871136791,Cold Mountain,Charles Frazier,1997,Atlantic Monthly Press,http://images.amazon.com/images/P/0871136791.0...,http://images.amazon.com/images/P/0871136791.0...,http://images.amazon.com/images/P/0871136791.0...,"Inman, a wounded soldier, walks away from the ...",191,3.308901
6,0515133302,Hemlock Bay,Catherine Coulter,2002,Jove Books,http://images.amazon.com/images/P/0515133302.0...,http://images.amazon.com/images/P/0515133302.0...,http://images.amazon.com/images/P/0515133302.0...,Caught up in a challenging probe into the kidn...,109,2.513761
7,0061097101,The Saving Graces: A Novel,Patricia Gaffney,2000,HarperTorch,http://images.amazon.com/images/P/0061097101.0...,http://images.amazon.com/images/P/0061097101.0...,http://images.amazon.com/images/P/0061097101.0...,A mesmerizing story about true friendship foll...,219,2.835616
8,0679731725,The Remains of the Day (Vintage International),Kazuo Ishiguro,1993,Vintage Books USA,http://images.amazon.com/images/P/0679731725.0...,http://images.amazon.com/images/P/0679731725.0...,http://images.amazon.com/images/P/0679731725.0...,An English butler reflects--sometimes bitterly...,102,2.823529
9,034536676X,The World According to Garp,John Irving,1994,Ballantine Books,http://images.amazon.com/images/P/034536676X.0...,http://images.amazon.com/images/P/034536676X.0...,http://images.amazon.com/images/P/034536676X.0...,"T. S. Garp, a man with high ambitions for an a...",108,4.472222

In [ ]:
recomdata = recomdata.drop(['rating-count','average-rating'], axis = 1 )

In [ ]:
recomdata.head(10)

,ISBN,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L,description
0,0671042858,The Girl Who Loved Tom Gordon,Stephen King,2000,Pocket,http://images.amazon.com/images/P/0671042858.0...,http://images.amazon.com/images/P/0671042858.0...,http://images.amazon.com/images/P/0671042858.0...,The acclaimed #1 New York Times and undisputed...
1,0440211727,A Time to Kill,JOHN GRISHAM,1992,Dell,http://images.amazon.com/images/P/0440211727.0...,http://images.amazon.com/images/P/0440211727.0...,http://images.amazon.com/images/P/0440211727.0...,Following the brutal rape of his ten-year-old ...
2,0425185710,Valhalla Rising (Dirk Pitt Adventures (Paperba...,Clive Cussler,2002,Berkley Publishing Group,http://images.amazon.com/images/P/0425185710.0...,http://images.amazon.com/images/P/0425185710.0...,http://images.amazon.com/images/P/0425185710.0...,Marine explorer Dirk Pitt must rely on the nau...
3,0515130389,Carolina Moon,Nora Roberts,2001,Jove Books,http://images.amazon.com/images/P/0515130389.0...,http://images.amazon.com/images/P/0515130389.0...,http://images.amazon.com/images/P/0515130389.0...,From the #1 New York Times bestselling author-...
4,0743411250,The Woman Next Door,Barbara Delinsky,2002,Pocket,http://images.amazon.com/images/P/0743411250.0...,http://images.amazon.com/images/P/0743411250.0...,http://images.amazon.com/images/P/0743411250.0...,New York Times bestselling author Barbara Deli...
5,0871136791,Cold Mountain,Charles Frazier,1997,Atlantic Monthly Press,http://images.amazon.com/images/P/0871136791.0...,http://images.amazon.com/images/P/0871136791.0...,http://images.amazon.com/images/P/0871136791.0...,"Inman, a wounded soldier, walks away from the ..."
6,0515133302,Hemlock Bay,Catherine Coulter,2002,Jove Books,http://images.amazon.com/images/P/0515133302.0...,http://images.amazon.com/images/P/0515133302.0...,http://images.amazon.com/images/P/0515133302.0...,Caught up in a challenging probe into the kidn...
7,0061097101,The Saving Graces: A Novel,Patricia Gaffney,2000,HarperTorch,http://images.amazon.com/images/P/0061097101.0...,http://images.amazon.com/images/P/0061097101.0...,http://images.amazon.com/images/P/0061097101.0...,A mesmerizing story about true friendship foll...
8,0679731725,The Remains of the Day (Vintage International),Kazuo Ishiguro,1993,Vintage Books USA,http://images.amazon.com/images/P/0679731725.0...,http://images.amazon.com/images/P/0679731725.0...,http://images.amazon.com/images/P/0679731725.0...,An English butler reflects--sometimes bitterly...
9,034536676X,The World According to Garp,John Irving,1994,Ballantine Books,http://images.amazon.com/images/P/034536676X.0...,http://images.amazon.com/images/P/034536676X.0...,http://images.amazon.com/images/P/034536676X.0...,"T. S. Garp, a man with high ambitions for an a..."

In [ ]:
recomdata.rename(columns = {'Book-Author':'author','Year-Of-Publication':'year', 'Book-Title':'title', 'Publisher': 'publisher','description':'summary'
                              }, inplace = True)

In [ ]:
recomdata.head(10)

,ISBN,title,author,year,publisher,Image-URL-S,Image-URL-M,Image-URL-L,summary
0,0671042858,The Girl Who Loved Tom Gordon,Stephen King,2000,Pocket,http://images.amazon.com/images/P/0671042858.0...,http://images.amazon.com/images/P/0671042858.0...,http://images.amazon.com/images/P/0671042858.0...,The acclaimed #1 New York Times and undisputed...
1,0440211727,A Time to Kill,JOHN GRISHAM,1992,Dell,http://images.amazon.com/images/P/0440211727.0...,http://images.amazon.com/images/P/0440211727.0...,http://images.amazon.com/images/P/0440211727.0...,Following the brutal rape of his ten-year-old ...
2,0425185710,Valhalla Rising (Dirk Pitt Adventures (Paperba...,Clive Cussler,2002,Berkley Publishing Group,http://images.amazon.com/images/P/0425185710.0...,http://images.amazon.com/images/P/0425185710.0...,http://images.amazon.com/images/P/0425185710.0...,Marine explorer Dirk Pitt must rely on the nau...
3,0515130389,Carolina Moon,Nora Roberts,2001,Jove Books,http://images.amazon.com/images/P/0515130389.0...,http://images.amazon.com/images/P/0515130389.0...,http://images.amazon.com/images/P/0515130389.0...,From the #1 New York Times bestselling author-...
4,0743411250,The Woman Next Door,Barbara Delinsky,2002,Pocket,http://images.amazon.com/images/P/0743411250.0...,http://images.amazon.com/images/P/0743411250.0...,http://images.amazon.com/images/P/0743411250.0...,New York Times bestselling author Barbara Deli...
5,0871136791,Cold Mountain,Charles Frazier,1997,Atlantic Monthly Press,http://images.amazon.com/images/P/0871136791.0...,http://images.amazon.com/images/P/0871136791.0...,http://images.amazon.com/images/P/0871136791.0...,"Inman, a wounded soldier, walks away from the ..."
6,0515133302,Hemlock Bay,Catherine Coulter,2002,Jove Books,http://images.amazon.com/images/P/0515133302.0...,http://images.amazon.com/images/P/0515133302.0...,http://images.amazon.com/images/P/0515133302.0...,Caught up in a challenging probe into the kidn...
7,0061097101,The Saving Graces: A Novel,Patricia Gaffney,2000,HarperTorch,http://images.amazon.com/images/P/0061097101.0...,http://images.amazon.com/images/P/0061097101.0...,http://images.amazon.com/images/P/0061097101.0...,A mesmerizing story about true friendship foll...
8,0679731725,The Remains of the Day (Vintage International),Kazuo Ishiguro,1993,Vintage Books USA,http://images.amazon.com/images/P/0679731725.0...,http://images.amazon.com/images/P/0679731725.0...,http://images.amazon.com/images/P/0679731725.0...,An English butler reflects--sometimes bitterly...
9,034536676X,The World According to Garp,John Irving,1994,Ballantine Books,http://images.amazon.com/images/P/034536676X.0...,http://images.amazon.com/images/P/034536676X.0...,http://images.amazon.com/images/P/034536676X.0...,"T. S. Garp, a man with high ambitions for an a..."

In [ ]:

print(pickle.format_version)

4.0

In [ ]:
import pickle

In [ ]:
with open('recomdata.pickle', 'wb') as handle:
    pickle.dump(recomdata, handle)

get books having average rating >=3

In [ ]:
popularbooks=popularbooks[popularbooks['average-rating'] >=3]